version: '3.8'

services:
  app:
    build: .
    container_name: symfony_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    environment:
      APP_ENV: dev
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"